import { StyleSheet } from 'react-native';

export const colors = { paper: '#F7F5EF', white: '#FFFFFF', ink: '#203D34', forest: '#244D40', sage: '#E8EEE5', muted: '#667060', line: '#E3E5DB', gold: '#C9AC6A', sand: '#EEE8DC', danger: '#994F45' };
export const fonts = { regular: 'DMSans_400Regular', medium: 'DMSans_500Medium', bold: 'DMSans_600SemiBold', serif: 'CormorantGaramond_500Medium', serifBold: 'CormorantGaramond_600SemiBold' };
export const s = StyleSheet.create({
  outer: { flex: 1, backgroundColor: '#E9ECE5', alignItems: 'center' },
  shell: { width: '100%', maxWidth: 480, flex: 1, backgroundColor: colors.paper, overflow: 'hidden' },
  body: { paddingHorizontal: 24, paddingTop: 12, paddingBottom: 32, gap: 24 },
  row: { flexDirection: 'row', alignItems: 'center' },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  stack: { gap: 14 },
  text: { fontFamily: fonts.regular, fontSize: 14, lineHeight: 22, color: colors.ink },
  muted: { fontFamily: fonts.regular, fontSize: 12, lineHeight: 19, color: colors.muted },
  tiny: { fontFamily: fonts.medium, fontSize: 10, lineHeight: 16, color: colors.muted },
  eyebrow: { fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1.8, color: colors.muted },
  title: { fontFamily: fonts.serif, fontSize: 46, lineHeight: 47, color: colors.ink, letterSpacing: -1.3 },
  heading: { fontFamily: fonts.serifBold, fontSize: 28, lineHeight: 31, color: colors.ink },
  medium: { fontFamily: fonts.bold, fontSize: 14, lineHeight: 21, color: colors.ink },
  iconButton: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' },
  brand: { fontFamily: fonts.bold, letterSpacing: 3.8, fontSize: 14, color: colors.ink },
  logo: { width: 35, height: 35, borderRadius: 18, backgroundColor: colors.forest, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  hero: { backgroundColor: colors.forest, borderRadius: 24, padding: 24, overflow: 'hidden', minHeight: 221 },
  heroTitle: { fontFamily: fonts.serif, color: colors.paper, fontSize: 33, lineHeight: 35, maxWidth: 235, marginTop: 14, marginBottom: 18 },
  heroAction: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.paper, borderRadius: 14, paddingHorizontal: 17, minHeight: 49, width: 196 },
  card: { backgroundColor: colors.white, borderRadius: 20, padding: 20, borderWidth: 1, borderColor: colors.line },
  softCard: { backgroundColor: colors.sage, borderRadius: 20, padding: 20 },
  pill: { backgroundColor: colors.sage, borderRadius: 20, paddingVertical: 5, paddingHorizontal: 10 },
  progressTrack: { height: 5, backgroundColor: colors.sand, borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: colors.forest, borderRadius: 3 },
  habitRow: { flexDirection: 'row', alignItems: 'center', gap: 13, minHeight: 72, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.line },
  habitIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.sage },
  check: { width: 26, height: 26, borderRadius: 13, borderWidth: 1.5, borderColor: '#C8CEC1', alignItems: 'center', justifyContent: 'center' },
  checkOn: { backgroundColor: colors.forest, borderColor: colors.forest },
  weekCell: { flex: 1, alignItems: 'center', gap: 9 },
  weekDot: { width: 33, height: 33, borderRadius: 17, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line },
  quote: { fontFamily: fonts.serif, fontSize: 25, lineHeight: 31, color: colors.ink },
  source: { fontFamily: fonts.medium, fontSize: 11, color: colors.forest, textDecorationLine: 'underline' },
  linkButton: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 6 },
  button: { minHeight: 54, borderRadius: 16, paddingHorizontal: 20, backgroundColor: colors.forest, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9 },
  buttonText: { fontFamily: fonts.bold, fontSize: 14, color: colors.white },
  secondary: { backgroundColor: colors.sage },
  tabbar: { flexDirection: 'row', backgroundColor: colors.paper, borderTopWidth: 1, borderTopColor: colors.line, paddingHorizontal: 12, paddingTop: 10 },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center', minHeight: 60, gap: 6 },
  tabIcon: { width: 46, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  tabText: { fontFamily: fonts.medium, fontSize: 10, color: colors.muted },
  input: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.paper, padding: 14, fontFamily: fonts.regular, fontSize: 14, color: colors.ink },
  chip: { minHeight: 48, paddingHorizontal: 16, borderRadius: 24, borderWidth: 1, borderColor: colors.line, justifyContent: 'center', marginRight: 8 },
  chipOn: { backgroundColor: colors.forest, borderColor: colors.forest },
  roundSlot: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line },
  counter: { width: 258, height: 258, borderRadius: 129, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', backgroundColor: colors.sage },
  counterNumber: { fontFamily: fonts.serif, fontSize: 82, lineHeight: 92, color: colors.forest },
  modalShade: { flex: 1, backgroundColor: 'rgba(23,45,36,.36)', justifyContent: 'flex-end', alignItems: 'center' },
  sheet: { width: '100%', maxWidth: 480, maxHeight: '92%', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24, backgroundColor: colors.paper },
  handle: { alignSelf: 'center', width: 40, height: 4, borderRadius: 2, backgroundColor: '#CFD3C7', marginBottom: 16 },
  toast: { position: 'absolute', left: 20, right: 20, bottom: 98, backgroundColor: colors.ink, padding: 16, borderRadius: 16 },
  empty: { alignItems: 'center', paddingVertical: 25, gap: 16 },
  error: { backgroundColor: '#F4E6E0', padding: 14, borderRadius: 12 },
  pressed: { opacity: .7 },
});
